version: '3'
services: 
    angularnginx:
        build: angular
    nodeservice:
        build: server
        ports: 
         - "3000:3000"
        links: 
         - mymongodb
    mymongodb: 
        image: mongo
        ports:
         - "27017:27017"